version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: rfid_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: rfid_db
      TZ: America/Guayaquil
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  node:
    build: ./api
    container_name: rfid_node
    ports:
      - "3000:3000"
    depends_on:
      - postgres